version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - mysql-symfony:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile-php
    ports:
      - '9000:9000'
    volumes:
      - ./symfony:/var/www/symfony
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8050:80'
    volumes:
      - ./symfony:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
volumes:
  mysql-symfony:
