version: '3.8'

services:
  database:
    container_name: database-express
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: express
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '5306:3306'
    volumes:
      - mysql-express:/var/lib/mysql

  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./node:/var/www/node
    depends_on:
      - database

volumes:
  mysql-express:

  
